<?php
    session_start();

    unset($_SESSION["userhr"]);
    unset($_SESSION["passhr"]);
    unset($_SESSION["designationhr"]);
    unset($_SESSION["VoirMenuProduitshr"]);
    unset($_SESSION["VoirMenuParametreshr"]);
    unset($_SESSION["VoirCategorie1hr"]);
    unset($_SESSION["VoirCategorie2hr"]);
    unset($_SESSION["VoirCategorie3hr"]);
    unset($_SESSION["VoirCategorie4hr"]);
    unset($_SESSION["VoirCategorie5hr"]);
    unset($_SESSION["VoirCategorie6hr"]);
    unset($_SESSION["VoirCategorie7hr"]);
    unset($_SESSION["VoirCategorie8hr"]);
    unset($_SESSION["VoirCategorie9hr"]);
    unset($_SESSION["VoirCategorie20hr"]);
    unset($_SESSION["VoirCategorie25hr"]);
    unset($_SESSION["AjoutCategorie1hr"]);
    unset($_SESSION["AjoutCategorie2hr"]);
    unset($_SESSION["AjoutCategorie3hr"]);
    unset($_SESSION["AjoutCategorie4hr"]);
    unset($_SESSION["AjoutCategorie5hr"]);
    unset($_SESSION["AjoutCategorie6hr"]);
    unset($_SESSION["AjoutCategorie7hr"]);
    unset($_SESSION["AjoutCategorie8hr"]);
    unset($_SESSION["AjoutCategorie9hr"]);
    unset($_SESSION["AjoutCategorie20hr"]);
    unset($_SESSION["AjoutCategorie25hr"]);
    unset($_SESSION["VoirActionhr"]);
    unset($_SESSION["VoirTarifhr"]);
    unset($_SESSION["VoirAdminhr"]);
    unset($_SESSION["VoirPlanhr"]);
    unset($_SESSION["ModifCategoriehr"]);
    $_SESSION["userhr"] = '';
    $_SESSION["passhr"] = '';
    $_SESSION["designationhr"] = '';
    $_SESSION["VoirMenuProduitshr"] = '';
    $_SESSION["VoirMenuParametreshr"] = '';
    $_SESSION["VoirCategorie1hr"] = '';
    $_SESSION["VoirCategorie2hr"] = '';
    $_SESSION["VoirCategorie3hr"] = '';
    $_SESSION["VoirCategorie4hr"] = '';
    $_SESSION["VoirCategorie5hr"] = '';
    $_SESSION["VoirCategorie6hr"] = '';
    $_SESSION["VoirCategorie7hr"] = '';
    $_SESSION["VoirCategorie8hr"] = '';
    $_SESSION["VoirCategorie9hr"] = '';
    $_SESSION["VoirCategorie20hr"] = '';
    $_SESSION["VoirCategorie25hr"] = '';
    $_SESSION["AjoutCategorie1hr"] = '';
    $_SESSION["AjoutCategorie2hr"] = '';
    $_SESSION["AjoutCategorie3hr"] = '';
    $_SESSION["AjoutCategorie4hr"] = '';
    $_SESSION["AjoutCategorie5hr"] = '';
    $_SESSION["AjoutCategorie6hr"] = '';
    $_SESSION["AjoutCategorie7hr"] = '';
    $_SESSION["AjoutCategorie8hr"] = '';
    $_SESSION["AjoutCategorie9hr"] = '';
    $_SESSION["AjoutCategorie20hr"] = '';
    $_SESSION["AjoutCategorie25hr"] = '';
    $_SESSION["VoirActionhr"] = '';
    $_SESSION["VoirTarifhr"] = '';
    $_SESSION["VoirAdminhr"] = '';
    $_SESSION["VoirPlanhr"] = '';
    $_SESSION["ModifCategoriehr"] = '';
?>